# Generated by Django 2.2.6 on 2020-01-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_testrecord_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
