# Generated by Django 2.2.6 on 2020-01-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teststore',
            fields=[
                ('storeid', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('prolist', models.CharField(max_length=1024000)),
            ],
        ),
        migrations.AlterField(
            model_name='paper',
            name='prolist',
            field=models.CharField(max_length=102400),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='answers',
            field=models.CharField(max_length=102400),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='keguan_detail',
            field=models.CharField(max_length=102400),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='zhuguan_detail',
            field=models.CharField(max_length=102400),
        ),
    ]
